/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rmorales1
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        txtNumeroDeFilas.setEditable(true);
        txtNumeroDeColumnas.setEditable(true);
        cmdCrear.setEnabled(true);
        cmdLlenadoManual.setEnabled(false);
        cmdLlenadoAutomatico.setEnabled(false);
        cmdOperacion.setEnabled(false);
        cmdLimpiar.setEnabled(true);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNumeroDeFilas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNumeroDeColumnas = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtNumerodeFilas1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNumerodeColumnas1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtNumerodeFilas3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNumerodeColumnas3 = new javax.swing.JTextField();
        cmdCrear = new javax.swing.JButton();
        cmdLlenadoManual = new javax.swing.JButton();
        cmdLlenadoAutomatico = new javax.swing.JButton();
        cmdOperacion = new javax.swing.JButton();
        cmdLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTablaResultado = new javax.swing.JTable();
        cmbOperaciones = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTablaInicial = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Matrices I"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("JasmineUPC", 3, 36)); // NOI18N
        jLabel1.setText("Operaciones Matrices");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 310, 40));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Iniciales"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("No. de Filas:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 20));

        txtNumeroDeFilas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroDeFilasKeyTyped(evt);
            }
        });
        jPanel2.add(txtNumeroDeFilas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 60, -1));

        jLabel3.setText("No. de Columnas: ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, 20));

        txtNumeroDeColumnas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroDeColumnasKeyTyped(evt);
            }
        });
        jPanel2.add(txtNumeroDeColumnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 60, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Iniciales"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("No. de Filas:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 20));
        jPanel3.add(txtNumerodeFilas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 30, -1));

        jLabel5.setText("No. de Columnas: ");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, 20));
        jPanel3.add(txtNumerodeColumnas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 30, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 350, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 380, 60));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Iniciales"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("No. de Filas:");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 20));
        jPanel5.add(txtNumerodeFilas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 30, -1));

        jLabel9.setText("No. de Columnas: ");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, 20));
        jPanel5.add(txtNumerodeColumnas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 30, -1));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 350, 60));

        cmdCrear.setText("Crear");
        cmdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearActionPerformed(evt);
            }
        });
        jPanel4.add(cmdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        cmdLlenadoManual.setText("Manual");
        jPanel4.add(cmdLlenadoManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        cmdLlenadoAutomatico.setText("Automático");
        cmdLlenadoAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenadoAutomaticoActionPerformed(evt);
            }
        });
        jPanel4.add(cmdLlenadoAutomatico, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        cmdOperacion.setText("Operacion");
        cmdOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdOperacionActionPerformed(evt);
            }
        });
        jPanel4.add(cmdOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel4.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 480, 60));

        tblTablaResultado.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tblTablaResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblTablaResultado);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, 370, 300));

        cmbOperaciones.setBackground(new java.awt.Color(204, 204, 255));
        cmbOperaciones.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbOperaciones.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Diagonal secundaria.", "Triangular superior.", "Triangular inferior.", "Traspuesta a la ingresada.", " Letra A.", " Letra Z.", " Letra T.", " Letra V.", " Letra E.", " Letra F.", " Letra P.", " Letra I.", " Letra N.", " Letra Y.", " Letra X." }));
        jPanel1.add(cmbOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 180, 30));

        tblTablaInicial.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tblTablaInicial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblTablaInicial);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 380, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1082, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1098, 612));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearActionPerformed
       if (txtNumeroDeFilas.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese No. Filas", "Error", JOptionPane.ERROR_MESSAGE);
           
           
            txtNumeroDeFilas.setEditable(true);
            txtNumeroDeColumnas.setEditable(true);
            
            txtNumeroDeFilas.requestFocusInWindow();
            
        } else if (txtNumeroDeColumnas.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese No. Columnas", "Error", JOptionPane.ERROR_MESSAGE);
            
            
            txtNumeroDeFilas.setEditable(true);
            txtNumeroDeColumnas.setEditable(true);
            
            txtNumeroDeColumnas.requestFocusInWindow();
        } else {
            int nf, nc;
            DefaultTableModel tm, tm2;
            
            nf = Integer.parseInt(txtNumeroDeFilas.getText());
            nc = Integer.parseInt(txtNumeroDeColumnas.getText());
            
            if (nf == 0) {
                JOptionPane.showMessageDialog(this, "No. Filas no puede ser cero", "Error", JOptionPane.ERROR_MESSAGE);
                
                
                txtNumeroDeFilas.setEditable(true);
                txtNumeroDeColumnas.setEditable(true);
                
                txtNumeroDeFilas.requestFocusInWindow();
            } else if (nc == 0) {
                JOptionPane.showMessageDialog(this, "No. Columnas no puede ser cero", "Error", JOptionPane.ERROR_MESSAGE);
               
                
                txtNumeroDeFilas.setEditable(true);
                txtNumeroDeColumnas.setEditable(true);
               
                 txtNumeroDeColumnas.requestFocusInWindow();
            } else {
                tm = (DefaultTableModel) tblTablaInicial.getModel();
                tm2 = (DefaultTableModel) tblTablaResultado.getModel();
                
                tm.setRowCount(nf);
                tm.setColumnCount(nc);
                
                tm2.setRowCount(nf);
                tm2.setColumnCount(nc);
                
                
                txtNumeroDeFilas.setEditable(false);
                txtNumeroDeColumnas.setEditable(false);
                cmdCrear.setEnabled(false);
                cmdLlenadoManual.setEnabled(false);
                cmdLlenadoAutomatico.setEnabled(true);
                cmdOperacion.setEnabled(false);
                cmdLimpiar.setEnabled(true);
            }
        }

    }//GEN-LAST:event_cmdCrearActionPerformed

    private void cmdLlenadoAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenadoAutomaticoActionPerformed
        int nf, nc, n;
        
        nc = tblTablaInicial.getColumnCount();
        nf = tblTablaInicial.getRowCount();
        
        for (int i = 0; i < nf; i++) {
            for (int j = 0; j < nc; j++) {
                n = (int) (Math.random() * 50 + 1);
                tblTablaInicial.setValueAt(n, i, j);
            }
            
        }
        cmdOperacion.setEnabled(true);

    }//GEN-LAST:event_cmdLlenadoAutomaticoActionPerformed

    private void cmdOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdOperacionActionPerformed
        
        int op, nf, nc, aux, cont = 0,s = 0;
        op = cmbOperaciones.getSelectedIndex();
        
        nf = tblTablaInicial.getRowCount();
        nc = tblTablaInicial.getColumnCount();
        
        switch (op) {
            case 0:
                if (nf != nc) {
                    JOptionPane.showMessageDialog(this, "Si desea realizar esta operación debe ingresar el mismo valor en No. Filas y en No. Columnas ", "Error", JOptionPane.ERROR_MESSAGE);
                    
                } else{
                for (int i = 0; i < nf; i++) {
                     for (int j=0; j < nc; j++)  {
                        aux = (int) tblTablaInicial.getValueAt(i, j);
                         if ( j + i == s+nc){
                         tblTablaResultado.setValueAt(aux,i, j);
                        }
                    }
                    
                }
                }
  
                break;
                
                 case 1:
                for (int i = 0; i < nf-1; i++) {
                     for (int j=0; j > nc ; j--)  {
                        aux = (int) tblTablaInicial.getValueAt(i, j);
                         if (i <= j){
                         tblTablaResultado.setValueAt(aux,i, j);
                        }
                    }
                    
                }
  
                break;
                 case 2:
                for (int i = 0; i < nf-1; i++) {
                     for (int j=0; j < nc ; j--)  {
                        aux = (int) tblTablaInicial.getValueAt(i, j);
                         if ( i ==nc - nf){
                         tblTablaResultado.setValueAt(aux,i, j);
                        }
                    }
                    
                }
  
                break;
                 case 3:
                for (int i = 0; i < nc; i++) {
                     for (int j=0; j < nf; j++)  {
                        aux = (int) tblTablaInicial.getValueAt(i, j);
                         if (i == nc || j == nf ){
                         tblTablaResultado.setValueAt(aux,i, j);
                        }
                    }
                    
                }
  
                break;
                case 4:
                for (int i = 0; i < nf; i++) {
                     for (int j=0; j < nc; j++)  {
                        aux = (int) tblTablaInicial.getValueAt(i, j);
                         if ( i == 0 || j==0 || j== nc-1 || i==(nf-1)/2  ){
                         tblTablaResultado.setValueAt(aux,i, j);
                        }
                    }
                    
                }
  
                break;
                case 5:
                for (int i = 0; i < nf; i++) {
                     for (int j=0; j < nc; j++)  {
                        aux = (int) tblTablaInicial.getValueAt(i, j);
                         if ( i == nf - 1|| nc - 1 - i == j || i == 0 ){
                         tblTablaResultado.setValueAt(aux,i, j);
                        }
                    }
                    
                }
  
                break;
                
                case 6:
                for (int i = 0; i < nf; i++) {
                     for (int j=0; j < nc; j++)  {
                        aux = (int) tblTablaInicial.getValueAt(i, j);
                         if (i == 0 || j == (nc - 1) / 2){
                         tblTablaResultado.setValueAt(aux,i, j);
                        }
                    }
                    
                }
  
                break;
                case 7:
                for (int i = 0; i < nf; i++) {
                     for (int j=0; j < nc; j++)  {
                        aux = (int) tblTablaInicial.getValueAt(i, j);
                         if ( i == 0 || i == nf - 1 || j == 0){
                         tblTablaResultado.setValueAt(aux,i, j);
                        }
                    }
                    
                }
  
                break;
                 case 8:
                for (int i = 0; i < nf; i++) {
                     for (int j=0; j < nc; j++)  {
                        aux = (int) tblTablaInicial.getValueAt(i, j);
                         if ( i == 0 || i == nf - 1 || i == (nf - 1) / 2 || j == 0 ){
                         tblTablaResultado.setValueAt(aux,i, j);
                        }
                    }
                    
                }
  
                break;
                case 9:
                for (int i = 0; i < nf; i++) {
                    for (int j = 0; j < nc; j++) {
                        aux = (int) tblTablaInicial.getValueAt(i, j);
                        if (i == 0 || i == (nf - 1) / 2 || j == 0) {
                            tblTablaResultado.setValueAt(aux, i, j);
                        }
                    }
                }
                break;
            case 10:
                for (int i = 0; i < nf; i++) {
                    for (int j = 0; j < nc; j++) {
                        aux = (int) tblTablaInicial.getValueAt(i, j);
                        if (i == 0 || i == (nf - 1) / 2 || j == 0||j == nc+1) {
                            
                            tblTablaResultado.setValueAt(aux, i, j);
                        }
                    }
                }
                break;
            case 11:
                for (int i = 0; i < nf; i++) {
                    for (int j = 0; j < nc; j++) {
                        aux = (int) tblTablaInicial.getValueAt(i, j);
                        if (i == 0 || j == (nc - 1) / 2 || i == nf - 1) {
                            tblTablaResultado.setValueAt(aux, i, j);
                        }
                    }
                }
                break;
            case 12:
                for (int i = 0; i < nf; i++) {
                    for (int j = 0; j < nc; j++) {
                        aux = (int) tblTablaInicial.getValueAt(i, j);
                        if (i == j || j == nf - 1 || j == 0) {
                            tblTablaResultado.setValueAt(aux, i, j);
                        }
                    }
                }
                break;
            case 13:
                for (int i = 0; i < nf; i++) {
                    for (int j = 0; j < nc; j++) {
                        aux = (int) tblTablaInicial.getValueAt(i, j);
                        if (i == j) {
                            tblTablaResultado.setValueAt(aux, i, j);
                        }
                    }
                }
                break;
            case 14:
                for (int i = 0; i < nf; i++) {
                    for (int j = 0; j < nc; j++) {
                        aux = (int) tblTablaInicial.getValueAt(i, j);
                        if (j == 0 || j == nc - 1 || i == (nf - 1) / 2) {
                            tblTablaResultado.setValueAt(aux, i, j);
                        }
                    }
                }
                break;
            
        }
        

    }//GEN-LAST:event_cmdOperacionActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
        
        DefaultTableModel tm, tm2;
        
        txtNumeroDeFilas.setText("");
        txtNumeroDeColumnas.setText("");
        
        txtNumeroDeFilas.requestFocusInWindow();
        cmbOperaciones.setSelectedIndex(0);
        
        txtNumeroDeFilas.setEditable(true);
        txtNumeroDeColumnas.setEditable(true);
        cmdCrear.setEnabled(true);
        cmdLlenadoManual.setEnabled(false);
        cmdLlenadoAutomatico.setEnabled(false);
        cmdOperacion.setEnabled(false);
        cmdLimpiar.setEnabled(true);
       
        
        tm = (DefaultTableModel) tblTablaInicial.getModel();
        tm2 = (DefaultTableModel) tblTablaResultado.getModel();
        
        tm.setRowCount(0);
        tm.setColumnCount(0);
        
        tm2.setRowCount(0);
        tm2.setColumnCount(0);

    }//GEN-LAST:event_cmdLimpiarActionPerformed

    private void txtNumeroDeColumnasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroDeColumnasKeyTyped
      char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNumeroDeColumnasKeyTyped

    private void txtNumeroDeFilasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroDeFilasKeyTyped
       char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNumeroDeFilasKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbOperaciones;
    private javax.swing.JButton cmdCrear;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JButton cmdLlenadoAutomatico;
    private javax.swing.JButton cmdLlenadoManual;
    private javax.swing.JButton cmdOperacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblTablaInicial;
    private javax.swing.JTable tblTablaResultado;
    private javax.swing.JTextField txtNumeroDeColumnas;
    private javax.swing.JTextField txtNumeroDeFilas;
    private javax.swing.JTextField txtNumerodeColumnas1;
    private javax.swing.JTextField txtNumerodeColumnas3;
    private javax.swing.JTextField txtNumerodeFilas1;
    private javax.swing.JTextField txtNumerodeFilas3;
    // End of variables declaration//GEN-END:variables
}
